# Generated by Django 3.0.7 on 2021-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculties'},
        ),
    ]
