# Generated by Django 3.0.7 on 2021-05-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='university.Course'),
        ),
    ]
