# Generated by Django 3.0.7 on 2021-05-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20210509_2316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('course', 'score')},
        ),
    ]
