# Generated by Django 3.0.7 on 2021-05-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20210510_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='university.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='results',
            field=models.ManyToManyField(related_name='students', through='university.Score', to='university.Course'),
        ),
    ]
