# Generated by Django 3.0.7 on 2021-05-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20210510_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_course_scores',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_student_course_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='results',
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('course', 'score'), name='unique_course_score'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Score'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='scores',
            field=models.ManyToManyField(related_name='students', through='university.StudentScore', to='university.Score'),
        ),
    ]
