# Generated by Django 3.0.7 on 2021-05-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='university.Score'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='university.Student'),
        ),
    ]
